options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image from TRUEFIBACKEND/Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/truefi/truefi-backend:$SHORT_SHA',
      '-f', 'TRUEFIBACKEND/Dockerfile',
      'TRUEFIBACKEND'
    ]

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/truefi/truefi-backend:$SHORT_SHA'
    ]

  # Deploy to Cloud Run with Cloud SQL connection
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'truefi-backend',
      '--image', 'gcr.io/truefi/truefi-backend:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--add-cloudsql-instances', 'truefi:us-central1:true-fi-db',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10'
    ]

images:
  - 'gcr.io/truefi/truefi-backend:$SHORT_SHA'